### ISSUE TITLE
Mails fail in delivering to testauskoira

### ISSUE THREAD

**Issue by romeq** [Testausserveri/koirameili#3]
Mails fail to deliver if server where mail was sent from requires TLS on testauskoira.

[this](https://github.com/Testausserveri/koirameili/commit/68606b8f3faa28d4aca23c42b3dacad5aecd82b4) may explain why this happens.

![image](https://user-images.githubusercontent.com/83234299/143721856-d55004e5-a81d-46d4-9f90-3565eb7b061c.jpeg)

**Comment by ahnl** [comment]
Reverted commit https://github.com/Testausserveri/koirameili/commit/68606b8f3faa28d4aca23c42b3dacad5aecd82b4. 

Now it uses TLS again, but as far as I remember it uses an untrusted certificate. It still should work for almost everyone, but some email senders will refuse to deliver it. Maybe a Let's Encrypt certificate should do the trick. I'll look into it.

**Comment by Chicken** [comment]
A Let's Encrypt cert should totally work. Getting a valid cert instead of disabling TLS is much sensible solution. There should have always been a certificate. Why would you push anything to production with snakeoil security? How would you ever even arrive at the conclusion that disabling TLS would be a great idea?

**Comment by developerfromjokela** [comment]
> A Let's Encrypt cert should totally work. Getting a valid cert instead of disabling TLS is much sensible solution. There should have always been a certificate. Why would you push anything to production with snakeoil security? How would you ever even arrive at the conclusion that disabling TLS would be a great idea?

Good question.

**Comment by Esinko** [comment]
> A Let's Encrypt cert should totally work. Getting a valid cert instead of disabling TLS is much sensible solution. There should have always been a certificate. Why would you push anything to production with snakeoil security? How would you ever even arrive at the conclusion that disabling TLS would be a great idea?

idk laziness? :p
Feel free to figure out how to set it up ;)

**Comment by ahnl** [comment]
The service isn't intended for receiving sensitive emails and its sole purpose is a throwaway email service - thus the decision of disabling the TLS was considered. Its side effect of TLS being required by some SMTP servers was unknown.

It should be easy to add a certificate.

[<img width="972" alt="SMTP server documentation" src="https://user-images.githubusercontent.com/46541386/143873279-9a96a10d-f366-463a-a4dc-87bccaf172d3.png">](https://nodemailer.com/extras/smtp-server/#tls-and-startls-notice)

**Comment by romeq** [comment]
Closing this as the issue was fixed
